# https://docs.streamlit.io/library/advanced-features/configuration

[global]

disableWidgetStateDuplicationWarning =  false
showWarningOnDirectExecution         =  true

[logger]

level                                = 'info'
messageFormat                        = '%(asctime)s %(message)s'

[client]

showErrorDetails                     =  true
toolbarMode                          = 'auto'
showSidebarNavigation                =  true

[runner]

magicEnabled                         =  true
postScriptGC                         =  true
fastReruns                           =  true
enforceSerializableSessionState      =  false
enumCoercion                         = 'nameOnly'

[browser]

gatherUsageStats                     =  false

[server]

fileWatcherType                      = 'auto'
cookieSecret                         =  false
runOnSave                            =  true
enableCORS                           =  true
enableXsrfProtection                 =  true
maxUploadSize                        =  200
maxMessageSize                       =  200
enableWebsocketCompression           =  false
enableStaticServing                  =  false

[theme]

base                                 = 'dark'
primaryColor                         = '#6595EE'
backgroundColor                      = '#000000'
secondaryBackgroundColor             = '#252525'
textColor                            = '#FFFFFF'
font                                 = 'sans serif'

#https://www.w3schools.com/colors/colors_names.asp
#https://htmlcolorcodes.com/
#PurpleMediumSlate* #7B70EE
#CornFlowerBlue*    #6595EE
#Blue*              #0065FF
#Orange             #FFA500
#DarkOrange         #FF8C00
#OrangeRed          #FF4500
#Gold               #FFD700
#Yellow             #FFFF00
#Lime               #00FF00
#Green*             #4CAF50
#Cyan               #00FFFF
#DeepSkyBlue        #00BFFF
#Maroon             #800000
#Silver             #C0C0C0
#Gray               #808080
